In [2]:
sequence = "CTTTCTGTCCCGCCCTTCCTCTGA"

print(sequence)

CTTTCTGTCCCGCCCTTCCTCTGA

In [3]:
print(len(sequence))

24

In [4]:
gene = "TP53"
organism = "Homo-sapiens"
sequence = "CTTTCTGTCCCGCCCTTCCTCTGA"
length = len(sequence)

print("Gene: ", gene)
print("Oraganusm: ", organism)
print("Sequence: ", sequence)
print("Length: ", length)

Gene:  TP53
Oraganusm:  Homo-sapiens
Sequence:  CTTTCTGTCCCGCCCTTCCTCTGA
Length:  24

In [5]:
base = input("Enter a nucleotide(A/T/C/G): ")

if base == "A":
    print("Adenine")
elif base == "T":
    print("Thymine")
elif base == "C":
    print("Cytosine")
elif base == "G":
    print("Guanine")
else:
    print("Invalid nucleotide")

Enter a nucleotide(A/T/C/G): A
Adenine

In [27]:
# DNA validation

sequence = "CTTTCTGTCXCGCCCTTCCTCTGA"

if "X" in sequence:
    print("Invalid DNA Sequence")
else:
    print("Valid DNA Sequence")

Invalid DNA Sequence

In [28]:
# another way to validate

sequence = "CTTTCTGTCCGCCCTTCCTCTGA"

valid_bases = "ATCG"

valid = True

for base in sequence:
    if base not in valid_bases:
        valid = False
        
if valid:
    print("Valid DNA Sequence")
else :
    print("Invalid DNA Sequence")

Valid DNA Sequence

In [29]:
# loops

sequence = "CTTTCTGTCCGCCCTTCCTCTGA"

for i in sequence:
    print(i)

C
T
T
T
C
T
G
T
C
C
G
C
C
C
T
T
C
C
T
C
T
G
A

In [30]:
# count

sequence = "CTTTCTGTCCGCCCTTCCTCTGA"

print("Number of Adenine: ", sequence.count("A"))
print("Number of Cytosine: ", sequence.count("C"))

Number of Adenine:  1
Number of Cytosine:  10

In [31]:
# Lists

genes = ["BRCA1", "TP53", "EGFR", "KRAS"]

print(genes)
print("Gene 1: ", genes[0])

['BRCA1', 'TP53', 'EGFR', 'KRAS']
Gene 1:  BRCA1

In [32]:
# Arrays

import numpy as np

lengths = np.array([100, 30, 40, 50, 60])

print(lengths)
print(lengths[0])

[100  30  40  50  60]
100

In [33]:
# example for array

expression = np.array([12.5, 15.2, 8.4, 20.1, 18.7])

print("Mean: ", np.mean(expression))
print("Maximum: ", np.max(expression))

Mean:  14.98
Maximum:  20.1

In [34]:
# Dictionaries

gene = {
    "name": "BRCA1",
    "organism": "Homo_sapiens",
    "chromosome": "17",
    "function": "DNA repair"
}

print(gene, "\n")
print("name: ", gene["name"])
print("organism: ", gene["organism"])
print("chromosome: ", gene["chromosome"])
print("function: ", gene["function"])

{'name': 'BRCA1', 'organism': 'Homo_sapiens', 'chromosome': '17', 'function': 'DNA repair'}

name:  BRCA1
organism:  Homo_sapiens
chromosome:  17
function:  DNA repair

In [35]:
# add another variable and value to the dictionary

gene["sequence"] = "ATGCGTAGT"

print(gene)

{'name': 'BRCA1', 'organism': 'Homo_sapiens', 'chromosome': '17', 'function': 'DNA repair', 'sequence': 'ATGCGTAGT'}

In [36]:
genes = {
    "BRCA1":{
        "organism": "Homo_sapiens",
        "chromosome": "17"
    },
    "TP53": {
        "organism": "Homo_sapiens",
        "chromosome": "17"      
    }
}

print(genes["BRCA1"])

print(genes["TP53"]["chromosome"])

{'organism': 'Homo_sapiens', 'chromosome': '17'}
17

In [37]:
# Dataframes

import pandas as pd

data = {
    "Gene": ["BRCA1", "TP53", "EGFR", "KRAS"],
    "Organism": ["Human", "Human", "Human", "Human"],
    "length": [1200, 1500, 1100, 980],
    "GC_Content":[45.2, 51.3,48.7,42.1]
}

df = pd.DataFrame(data)

print(df)

    Gene Organism  length  GC_Content
0  BRCA1    Human    1200        45.2
1   TP53    Human    1500        51.3
2   EGFR    Human    1100        48.7
3   KRAS    Human     980        42.1

In [38]:
df.shape

(4, 4)

In [39]:
df.describe()

            length  GC_Content
count     4.000000     4.00000
mean   1195.000000    46.82500
std     222.336082     4.02109
min     980.000000    42.10000
25%    1070.000000    44.42500
50%    1150.000000    46.95000
75%    1275.000000    49.35000
max    1500.000000    51.30000

In [40]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Gene        4 non-null      object
 1   Organism    4 non-null      object
 2   length      4 non-null      int64
 3   GC_Content  4 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 256.0+ bytes

In [41]:
df.head(5)

    Gene Organism  length  GC_Content
0  BRCA1    Human    1200        45.2
1   TP53    Human    1500        51.3
2   EGFR    Human    1100        48.7
3   KRAS    Human     980        42.1

In [42]:
df.tail(5)

    Gene Organism  length  GC_Content
0  BRCA1    Human    1200        45.2
1   TP53    Human    1500        51.3
2   EGFR    Human    1100        48.7
3   KRAS    Human     980        42.1

In [43]:
df.columns

Index(['Gene', 'Organism', 'length', 'GC_Content'], dtype='object')

In [44]:
# selecting columns

df["Gene"]

0    BRCA1
1     TP53
2     EGFR
3     KRAS
Name: Gene, dtype: object

In [45]:
# genes with GC content greater than 45%

df[df["GC_Content"] > 45]

    Gene Organism  length  GC_Content
0  BRCA1    Human    1200        45.2
1   TP53    Human    1500        51.3
2   EGFR    Human    1100        48.7

In [46]:
# sorting

df.sort_values("GC_Content")

# or

df.sort_values("GC_Content", ascending=False)

    Gene Organism  length  GC_Content
1   TP53    Human    1500        51.3
2   EGFR    Human    1100        48.7
0  BRCA1    Human    1200        45.2
3   KRAS    Human     980        42.1

In [49]:
# add a new column

df["Length_kb"] = df["length"]/1000
print(df)

    Gene Organism  length  GC_Content  Length_kb
0  BRCA1    Human    1200        45.2       1.20
1   TP53    Human    1500        51.3       1.50
2   EGFR    Human    1100        48.7       1.10
3   KRAS    Human     980        42.1       0.98

In [50]:
# Find genes with length greater than 1100

df[df["length"] > 1100]

    Gene Organism  length  GC_Content  Length_kb
0  BRCA1    Human    1200        45.2        1.2
1   TP53    Human    1500        51.3        1.5

In [51]:
# count genes with length greater than 1000

(df["length"] > 1000).sum()

3

In [53]:
# Find genes with both length > 1000 and GC content > 45

df[(df["length"] > 1000) & (df["GC_Content"] > 45)]

    Gene Organism  length  GC_Content  Length_kb
0  BRCA1    Human    1200        45.2        1.2
1   TP53    Human    1500        51.3        1.5
2   EGFR    Human    1100        48.7        1.1

In [55]:
# Compare average GC_Content by organism

df.groupby("Organism")["GC_Content"].mean()

Organism
Human    46.825
Name: GC_Content, dtype: float64